name: garde-actix-web build

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.rs"
      - "**Cargo.toml"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**Cargo.toml"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check format
        run: |
          rustup component add rustfmt
          cargo fmt --all --check

      - name: Check cranky
        run: |
          rustup component add clippy
          cargo install cargo-cranky --force
          cargo cranky --no-deps --all-features --tests -- -D warnings -D clippy::print_stdout

      - name: Check deny
        run: |
          cargo install cargo-deny --force
          cargo deny check licenses sources advisories

      - name: Run tests
        run: cargo test --all-features
