name: Publish release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: katyo/publish-crates@v2
      name: Cargo publish
      with:
        registry-token: ${{ secrets.CARGO_LOGIN }}
